---
- name: Deploy FDO Manufacturing Server
  hosts: fdo
  become: yes
  vars:
    rv_dns_prefix: "rendezvous"
    base_domain: "sandbox559.opentlc.com"
    rpm: true
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"
      
  - name: check if system is registered
    ansible.builtin.stat:
      path: /etc/insights-client/.registered
    register: registered
  
  - name: register the system
    when: not registered.stat.exists
    block:
    - name: Register with subscription manager
      ansible.builtin.shell: |
        subscription-manager register --username={{ rhuser }} --password={{ rhpassword }} --force
        subscription-manager role --set="Red Hat Enterprise Linux Server"
        subscription-manager service-level --set="Self-Support"
        subscription-manager usage --set="Development/Test"
        subscription-manager attach
        subscription-manager config --rhsm.manage_repos=1

    - name: Connect system to Red Hat
      ansible.builtin.shell: |
        rhc connect --username={{ rhuser }} --password={{ rhpassword }}
  
  - name: Deploy FDO Manufacturing Server
    ansible.builtin.include_role:
      name: community.fdo.deploy_manufacturing_server
    vars:
      rpm: "{{ rpm }}"
      manufacturing_server_rendezvous_info_dns: "{{ rv_dns_prefix }}.{{ base_domain }}"
      manufacturing_server_rendezvous_info_owner_port: 80
      manufacturing_server_rendezvous_info_deviceport: 80