---
# Install and configure FDO Rendezvous server
- name: Install and configure FDO Rendezvous Server
  hosts: rendezvous
  become: yes
  gather_facts: true

  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "./vars/secrets.yml"

  - name: check if system is registered
    ansible.builtin.stat:
      path: /etc/insights-client/.registered
    register: registered
        
  - name: register the system
    when: not registered.stat.exists
    block:
    - name: Register with subscription manager
      ansible.builtin.shell: |
        subscription-manager register --username={{ rhuser }} --password={{ rhpassword }} --force
        subscription-manager role --set="Red Hat Enterprise Linux Server"
        subscription-manager service-level --set="Self-Support"
        subscription-manager usage --set="Development/Test"
        subscription-manager attach
        subscription-manager config --rhsm.manage_repos=1

    - name: Connect system to Red Hat
      ansible.builtin.shell: |
        rhc connect --username={{ rhuser }} --password={{ rhpassword }}

  #- name: Create /etc/fdo/keys directory
  #  ansible.builtin.file:
  #    path: /etc/fdo/keys
  #    state: directory
  #    mode: '0755'

  #- name: Copy Manufacturer Certificate
  #  ansible.builtin.copy:
  #    src: "~/certs/manufacturer_cert.pem"
  #    dest: "/etc/fdo/keys/manufacturer_cert.pem"
  
  - name: Deploy Rendezvous server
    ansible.builtin.include_role:
      name: community.fdo.deploy_rendezvous_server
    vars:
      copy_manufacturer_certs: true