name: Build publish docs website to Github pages

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths-ignore:
        - ".gitignore"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
    publish:
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.publish.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
        - name: Publish to github pages
          id: publish
          uses: actions/deploy-pages@v4